apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-deployment
  namespace: default
spec:
  replicas: 3

  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato-container
        image: 472506472357.dkr.ecr.ap-south-1.amazonaws.com/zomato-app:latest
        ports:
        - containerPort: 3000
